.TH WORKSTATION 7
.SH NAME
workstation \- Manual for how to use this workstation
.SH SYNOPSIS
Gathering the common tools and examples to make this workstation useful in a variety of scenarios
.SH DESCRIPTION
.B autorandr
Set X11 display(s) to predefined configurations
.PP
.B arandr
Adjusting X11 display(s) on the fly - GUI
.PP
.B pavucontrol
Adjust audio levels for individual applications, inputs, and outputs - GUI
.PP
.B light
Output or adjust the existing brightness of the screen
