---
version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:v0.6.0
    steps:
      - checkout
      - run:
          name: Shell Linting
          command: for file in $(find . -type f \( -name "*.sh" -o -path "./bash/.bashrc.d/*" \)); do shellcheck --format=gcc $file; done;
  test:
    docker:
      - image: eugenmayer/make
    steps:
      - checkout
      - run:
          name: Doc Dir Check
          command: make -f GNUMakefile test-md
  test-tmux26:
    docker:
      - image: sarcasticadmin/tmux@sha256:8075057a34edafd8e348ac09b85bf8b23c0188fe6b24b785f46c4caffb1911b4
    steps:
      - checkout
      - run:
          name: Launch tmux config for 2.6
          command: test -f ./tmux/.tmux.conf && tmux -vv -f ./tmux/.tmux.conf new -d
      - run:
          name: Validate tmux config for 2.6
          command: cat tmux-* | grep 'invalid'; test $? -eq 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
      - test-tmux
