version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:v0.6.0
    steps:
      - checkout
      - run:
          name: Shell Linting
          command: for file in $(find . -type f -name "*.sh"); do shellcheck --format=gcc $file; done;
  test:
    docker:
      - image: eugenmayer/make
    steps:
      - checkout
      - run:
          name: Doc Dir Check
          command: make -f GNUMakefile test-md

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
