version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:v0.6.0
    steps:
      - checkout
      - run:
          name: Check for master branch merges
          command: if [[ -n "$(git log origin/master..HEAD --merges)" ]]; then echo "master was merged into this branch, please use \"git rebase\" instead"; exit 1; fi
      - run:
          name: Shell Linting
          command: for file in $(find ./bin -type f -name "*.sh"); do shellcheck --format=gcc $file; done;
  test:
    docker:
      - image: eugenmayer/make
    steps:
      - checkout
      - run:
          name: Doc Dir Check
          command: make -f GNUMakefile test-md
